---
- name: Check if OpenSRF config exists
  stat:
    path: "{{ opensrf_install_prefix }}/conf/opensrf.xml"
  register: opensrf_config
- name: Fail out if OpenSRF config doesn't exist
  fail:
    msg: "OpenSRF doesn't seem to be installed. Install OpenSRF before Evergreen."
  when: not opensrf_config.stat.exists
- name: Ensure Evergreen prerequisites are installed
  apt:
    name: "{{ evergreen_apt_requirements }}"
    state: present
    cache_valid_time: '3600'
- name: Download and unpack Evergreen tarball
  unarchive:
    src: "{{ evergreen_download_url }}"
    dest: "/home/{{ opensrf_system_user }}"
    owner: "{{ opensrf_system_user }}"
    group: "{{ opensrf_system_user }}"
    remote_src: yes
    creates: "{{ evergreen_src_directory }}/Open-ILS/src/extras/Makefile.common"
